export const SET_DOCTORLIST = "SET_DOCTORLIST";
export const UPDATE_DOCTORLIST = "UPDATE_DOCTORLIST";
export const GET_DRREQUEST = "GET_DRREQUEST";
export const GET_LABLIST = "GET_LABLIST";
export const GET_REQUESTLIST = "GET_REQUESTLIST";
export const GET_FETCHDOCTOR = "GET_FETCHDOCTOR";
export const GET_FETCHLAB = "GET_FETCHLAB";
export const GET_FETCHREQUEST = "GET_FETCHREQUEST";
